
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/euforic/matr"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/segmentio/ksuid"

[[override]]
  revision = "81aa34336d28aadc3a8e8da7dfd9258c5157e5e4"
  name = "k8s.io/api"

[[override]]
  revision = "3b05bbfa0a45413bfa184edbf9af617e277962fb"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "82aa063804cf055e16e8911250f888bc216e8b61"
